### ISSUE TITLE
Causes a "Pink Square" bug

### ISSUE THREAD

**Issue by Dark-Matter-001** [linuxgurugamer/TWR1#1]
1.34.0 in KSP 1.8.1

With and Without TWR1 installed: https://imgur.com/a/oRFvP4z

Mods: https://pastebin.com/WhGexhuH

**Comment by p3iurhgmc98h** [comment]
Can confirm that as of 1.34.0.1 in KSP 1.10.1 this is still an issue.
Update: Just realized that 1.34.0.2 is a later version (although marked as compatible with KSP 1.8.0-1.8.1 only); will test this version on KSP 1.11 later today.
Update 2: Yep, 1.34.0.2 fixed it.
